### ISSUE TITLE
Will the new updated tools work on Windows 7?

### ISSUE THREAD

**Issue by gillerby** [xenserver/xe-guest-utilities#115]
Title.

**Comment by xihuan-citrix** [comment]
Hi @gillerby , this is only for linux guest tools.

**Comment by gillerby** [comment]
> Hi @gillerby , this is only for linux guest tools.

Hi, thanks for the reply.
I'm asking because the following announcement said you're working on it:

**Comment by stormi** [comment]
This can be closed.
