### ISSUE TITLE
Would it be possible to tag a new release?

### ISSUE THREAD

**Issue by stormi** [xenserver/xe-guest-utilities#127]
There have been useful changes since last tag that happened more than one year ago, so I suggest to tag v7.31.0.

This would make it easier for packagers and downstreams to get a version with recent distros (ArchLinux, RHEL 9, that can have an enX prefix for network interfaces), and a smarter `xe-linux-distributions` based on `/etc/os-release`, among other changes.

**Comment by stormi** [comment]
Ping.

**Comment by xihuan-citrix** [comment]
Done
