### ISSUE TITLE
Build fails if the current directory is not named exactly `xe-guest-utilities`

### ISSUE THREAD

**Issue by stormi** [xenserver/xe-guest-utilities#128]
Since commit https://github.com/xenserver/xe-guest-utilities/commit/b9eebe3f9d934c232b7eeb5ce71e8ae0b9104593, the makefile looks for a vendor directory that is dynamically named after the current directory.

For example, if you're in directory `xe-guest-utilities-7.30`, it will look for `xe-guest-utilities-7.30/vendor/xe-guest-utilities-7.30`. This breaks the build because such directories don't exist. The only directory that exists is `./vendor/xe-guest-utilities`, but for this to work the directory that contains the sources must be named exactly `xe-guest-utilities`, so that `VENDOR_DIR` is computed as `xe-guest-utilities/vendor/xe-guest-utilities`.

I don't think the build process should depend this way on the name of the current directory.

**Comment by stormi** [comment]
Here's the concerned line:
```
VENDORDIR = $(REPO)/vendor/$(shell basename $(REPO))
```

**Comment by xihuan-citrix** [comment]
This should covert to a PR, let's try and submit anything can fix this

**Comment by stormi** [comment]
I would contribute a PR if I could, but I don't know why the VENDORDIR variable is currently defined this way so my naïve PR which would just change it to `VENDORDIR = $(REPO)/vendor/xe-guest-utilities` might break things if the name is expected to be different in some situations.

What should a fix look like, to you?

**Comment by xihuan-citrix** [comment]
PR https://github.com/xenserver/xe-guest-utilities/pulls raised
