### ISSUE TITLE
Remove citrix.repo, which seems unused

### ISSUE THREAD

**Issue by stormi** [xenserver/xe-guest-utilities#95]
The `citrix.repo` file, that is still distributed in the current RPMs built by Citrix, seems to me to be unused nowadays. The repository URL it points at is wrong and probably a thing of the past.

I suggest removing it from this repo and to remove references to it in spec files and such.

**Comment by stormi** [comment]
Any comment on this suggestion?

**Comment by stormi** [comment]
Gentle ping :)

**Comment by xihuan-citrix** [comment]
Let me have a test after removing the citrix.repo, if all are OK, then I will create a PR

**Comment by stormi** [comment]
Hi! Was the test successful?

**Comment by xihuan-citrix** [comment]
Hi @stormi, we actually use the file in our internal build, but actually we can remove this file to our internal build repo as it most citrix related and update the link.
